import {
  SLACK_HELP_COMMAND_ARGUMENT,
  SLACK_LIST_TASKS_COMMAND_ARGUMENT,
  SLACK_NEW_TASK_COMMAND_ARGUMENT,
  SLACK_UNKNOWN_COMMAND_ARGUMENT
} from '@utils/constants';

export const slackCommands = {
  [SLACK_HELP_COMMAND_ARGUMENT]: SLACK_HELP_COMMAND_ARGUMENT,
  [SLACK_LIST_TASKS_COMMAND_ARGUMENT]: SLACK_LIST_TASKS_COMMAND_ARGUMENT,
  [SLACK_NEW_TASK_COMMAND_ARGUMENT]: SLACK_NEW_TASK_COMMAND_ARGUMENT,
  [SLACK_UNKNOWN_COMMAND_ARGUMENT]: SLACK_UNKNOWN_COMMAND_ARGUMENT
};
